const cardNames = ["red-turn", "red-one", "red-two", "red-three", 
	"red-four", "red-five", "red-six", "red-seven", "red-eight", 
	"red-nine", "blue-turn", "blue-one", "blue-two", "blue-three",
	"blue-four", "blue-five", "blue-six", "blue-seven", "blue-eight", 
	"blue-nine", "green-turn", "green-one", "green-two", "green-three", 
	"green-four", "green-five", "green-six", "green-seven", "green-eight", 
	"green-nine", "yellow-turn", "yellow-one", "yellow-two", "yellow-three", 
	"yellow-four", "yellow-five", "yellow-six", "yellow-seven", "yellow-eight", 
	"yellow-nine", "red-buy-two", "blue-buy-two", "green-buy-two", "yellow-buy-two", 
	"red-block", "blue-block", "green-block", "yellow-block", "buy-four", "buy-four", 
	"change-color", "change-color", "red-turn", "red-one", "red-two", "red-three", 
	"red-four", "red-five", "red-six", "red-seven", "red-eight", 
	"red-nine", "blue-turn", "blue-one", "blue-two", "blue-three",
	"blue-four", "blue-five", "blue-six", "blue-seven", "blue-eight", 
	"blue-nine", "green-turn", "green-one", "green-two", "green-three", 
	"green-four", "green-five", "green-six", "green-seven", "green-eight", 
	"green-nine", "yellow-turn", "yellow-one", "yellow-two", "yellow-three", 
	"yellow-four", "yellow-five", "yellow-six", "yellow-seven", "yellow-eight", 
	"yellow-nine", "red-buy-two", "blue-buy-two", "green-buy-two", "yellow-buy-two", 
	"red-block", "blue-block", "green-block", "yellow-block", "buy-four", "buy-four", 
	"change-color", "change-color", "red-zero", "blue-zero", "green-zero", "yellow-zero"];

module.exports.cardNames = cardNames;